config-version = "2.7"
bind = "0.0.0.0:25565"
motd = "<bold><aqua>Agi<gray>-<light_purple>Craft </light_purple></bold><yellow>⪼</yellow> <gradient:light_purple:#ffffff>Заходи с версии</gradient> <white>1.21</white><gradient:white:aqua><newline>ОКАК <black>/otpor</black>"
show-max-players = 5090
# Online mode like in other servers
online-mode = false
# For online mode checking client brand
force-key-authentication = false
# Legacy mode (easy, only need bungeecord=true in spigot yml)
player-info-forwarding-mode = "legacy"

# Modern forward mode (more secure, need to specify keys in paper-global.yml)
# https://docs.papermc.io/velocity/player-information-forwarding/
# player-info-forwarding-mode = "modern"
# forwarding-secret-file = "forwarding.secret"

[servers]
airesearch = "airesearch:25570"
nanolimbo= "localhost:25579"
lobby = "lobby:25575"
survival = "survival:25571"
limbo = "limbo:25578"
# survival_plus = "survivalplus:25565"  # Coming soon

# Main default server for new players
default = "airesearch:25570"

# Global fallback server
fallback = "nanolimbo"

# Sequence of attempts
try = ["default", "nanolimbo", "lobby", "survival"]

[forced-hosts]
"research.nettyan.ru" = ["airesearch", "nanolimbo"]
"survival.nettyan.ru" = ["survival", "nanolimbo"]
"limbo.nettyan.ru" = ["nanolimbo"]

[advanced]
compression-threshold = 256
compression-level = -1
login-ratelimit = 3000
connection-timeout = 5000

[query]
# If query is enabled, on what port should the query protocol listen on?
port = 25565
show-plugins = true
# This is the map name that is reported to the query services.
map = "dust2"
# Whether to enable responding to GameSpy 4 query responses or not.
enabled = true
