config-version = "2.7"
bind = "0.0.0.0:25565"
motd = "<bold><aqua>Agi<gray>-<light_purple>Craft </light_purple></bold><yellow>⪼</yellow> <gradient:light_purple:#ffffff>Заходи с версии</gradient> <white>1.21</white><gradient:white:aqua><newline>ОКАК <black>/otpor</black>"
show-max-players = 100
online-mode = false
force-key-authentication = false
player-info-forwarding-mode = "legacy"

[servers]
ai_research = "airesearch:25570"
nanolimbo= "localhost:25579"
lobby = "lobby:25575"
survival = "survival:25571"
try = ["ai_research", "nanolimbo", "limbo", "lobby", "survival"]
# survival_plus = "survivalplus:25565"  # Coming soon

[forced-hosts]
"research.nettyan.ru" = ["ai_research", "nanolimbo"]
"survival.nettyan.ru" = ["survival", "nanolimbo"]

[advanced]
compression-threshold = 256
compression-level = -1
login-ratelimit = 3000
connection-timeout = 5000

[query]
# If query is enabled, on what port should the query protocol listen on?
port = 25565
show-plugins = true
# This is the map name that is reported to the query services.
map = "Velocity"
# Whether to enable responding to GameSpy 4 query responses or not.
enabled = true
